### ISSUE TITLE
Are the forces form alignn conservative?

### ISSUE THREAD

**Issue by CompRhys** [usnistgov/alignn#113]
https://github.com/usnistgov/alignn/blob/46334500cac9833125b3e444d65d0246e692bd61/alignn/models/alignn_atomwise.py#L367-L392

This snippet of code shows that the automatic differentiation is done with respect to the pairwise distances if using defaults. This means that the forces can only capture 2-body effects but the architecture models 3-body terms.

**Comment by bdecost** [comment]
Hi! thanks for your comment 

In principle, the forces should be conservative because we use autograd to compute $\frac{\partial E}{\partial \mathbf{r}_ij}$, where $\mathbf{r}_ij}$ are the relative position vectors (not the interatomic distance). Then we use a sum reduction to get the atomic forces $\frac{\partial E}{\partial \mathbf{r}_i}$ where the $\mathbf{r}_i$ are the cartesian coordinates. Currently ALIGNNAtomWise needs the configuration `add_reverse_forces=True` to account for both $\frac{\partial E}{\partial \mathbf{r}_ij}$ and $\frac{\partial E}{\partial \mathbf{r}_ji}$ in the reduction for $\frac{\partial E}{\partial \mathbf{r}_i}$.

[10.1103/physrevb.92.094301](https://doi.org/10.1103/physrevb.92.094301) has a nice derivation of this kind of force decomposition for the Tersoff potential, and I also [checked autograd vs LAMMPS forces](https://github.com/usnistgov/nfflr/blob/main/docs/source/notebooks/eam-forces.ipynb) for the Tersoff potential. (That project is pretty experimental still.)

In practice, looking over the code while writing this response I found a possible autograd mistake addressed by #114... I'm not positive the three body terms were being included in the autograd trace

I hope this addresses your concern? We've been using this approach so that we only have to store relative position vectors on the edge features instead of cell offsets, but I'm not sure it's worth the trouble.

**Comment by CompRhys** [comment]
Okay now I understand, main point of misunderstanding was belief that r was the distance in the code rather than the vector.

**Comment by bdecost** [comment]
cool - the notation in the code is not the clearest, unfortunately
